apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  Volumes:                       #A
  - name: foo
    secret:
      secretName: mysecret
  containers:
  - name: mycontainer
    image: redis
    volumeMounts:                #B
    - name: foo
      mountPath: /etc/foo
      readOnly: true

