apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret       #A
          key: username        #B
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret       #A
          key: password        #B

