apiVersion: apps/v1          #A
kind: Deployment
metadata:
  name: sample-app
spec:
  template:
    spec:
      containers:
      - name: sample-app     #B
        env:                 #C
        - name: DEBUG
          value: "true"
