apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: prod                         #A
  name: block-other-namespace
spec:
  podSelector: {}                              #B
  ingress:
  - from:
    - podSelector: {}                 #C
